version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: fornax-deps-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: fornax-deps-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            coverage run --source=fornax run_test.py
            coveralls
      - store_test_results:
          path: test-reports/
  deploy:
    steps:
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            make package
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload --repository-url https://test.pypi.org/legacy/ dist/*
    requires:
      - build
    filters:
      tags:
        only: /[0-9]+(\.[0-9]+)*/
      branches:
        ignore: /.*/